---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zk-0
  namespace: dingxin
spec:
  selector:
    matchLabels:
      app: zk
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zk
    spec:
      containers:
      - name: zk-0
        image: harbor-ui:30814/dingchat/zk:v3.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        env:
        - name: ZOO_MY_ID
          valueFrom: 
              configMapKeyRef: 
               name: dingxin-zk0-config
               key: ZOO_MY_ID
          #value: '0'
        - name: ZOO_SERVERS
          valueFrom:
              configMapKeyRef:
               name: dingxin-zk0-config
               key: ZOO_SERVERS

          # 注意！！k8s使用到virtual ip，因此，本机必须使用0.0.0.0 ip地址，否则本机zk启动会异常：
          # ERROR [zk1/10.0.0.251:3888:QuorumCnxManager$Listener@547] - Exception while listening
          # java.net.BindException: Address not available (Bind failed)错误
          #value: server.0=0.0.0.0:2888:3888 server.1=zk-1:2888:3888 server.2=zk-2:2888:3888
        volumeMounts:
        - name: zk-data
          mountPath: /data/zk-data
        - name: zk-logs
          mountPath: /data/zk-logs
      volumes:
      - name: zk-data
        persistentVolumeClaim:
          claimName: zk-0-data-pvc
      - name: zk-logs
        persistentVolumeClaim:
          claimName: zk-0-logs-pvc  
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zk-1
  namespace: dingxin
spec:
  selector:
    matchLabels:
      app: zk
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zk
    spec:
      containers:
      - name: zk-1
        image: harbor-ui:30814/dingchat/zk:v3.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        env:
        - name: ZOO_MY_ID
          valueFrom: 
              configMapKeyRef: 
               name: dingxin-zk1-config
               key: ZOO_MY_ID
          #value: '0'
        - name: ZOO_SERVERS
          valueFrom:
              configMapKeyRef:
               name: dingxin-zk1-config
               key: ZOO_SERVERS

          # 注意！！k8s使用到virtual ip，因此，本机必须使用0.0.0.0 ip地址，否则本机zk启动会异常：
          # ERROR [zk1/10.0.0.251:3888:QuorumCnxManager$Listener@547] - Exception while listening
          # java.net.BindException: Address not available (Bind failed)错误
          #value: server.0=0.0.0.0:2888:3888 server.1=zk-1:2888:3888 server.2=zk-2:2888:3888
        volumeMounts:
        - name: zk-data
          mountPath: /data/zk-data
        - name: zk-logs
          mountPath: /data/zk-logs
      volumes:
      - name: zk-data
        persistentVolumeClaim:
          claimName: zk-1-data-pvc
      - name: zk-logs
        persistentVolumeClaim:
          claimName: zk-1-logs-pvc  
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zk-2
  namespace: dingxin
spec:
  selector:
    matchLabels:
      app: zk
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zk
    spec:
      containers:
      - name: zk-2
        image: harbor-ui:30814/dingchat/zk:v3.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        env:
        - name: ZOO_MY_ID
          valueFrom: 
              configMapKeyRef: 
               name: dingxin-zk2-config
               key: ZOO_MY_ID
          #value: '0'
        - name: ZOO_SERVERS
          valueFrom:
              configMapKeyRef:
               name: dingxin-zk2-config
               key: ZOO_SERVERS

          # 注意！！k8s使用到virtual ip，因此，本机必须使用0.0.0.0 ip地址，否则本机zk启动会异常：
          # ERROR [zk1/10.0.0.251:3888:QuorumCnxManager$Listener@547] - Exception while listening
          # java.net.BindException: Address not available (Bind failed)错误
          #value: server.0=0.0.0.0:2888:3888 server.1=zk-1:2888:3888 server.2=zk-2:2888:3888
        volumeMounts:
        - name: zk-data
          mountPath: /data/zk-data
        - name: zk-logs
          mountPath: /data/zk-logs
      volumes:
      - name: zk-data
        persistentVolumeClaim:
          claimName: zk-2-data-pvc
      - name: zk-logs
        persistentVolumeClaim:
          claimName: zk-2-logs-pvc  
