---
kind: Service
apiVersion: v1
metadata:
  name: zk-0
  labels:
    app: zk
  namespace: dingxin
spec:
  ports:
  - name: client
    port: 2181
  - name: server
    port: 2888
  - name: leader-election
    port: 3888
  selector:
    app: zk

---
kind: Service
apiVersion: v1
metadata:
  name: zk-1
  labels:
    app: zk
  namespace: dingxin
spec:
  ports:
  - name: client
    port: 2181
  - name: server
    port: 2888
  - name: leader-election
    port: 3888
  selector:
    app: zk

---
kind: Service
apiVersion: v1
metadata:
  name: zk-2
  labels:
    app: zk
  namespace: dingxin
spec:
  ports:
  - name: client
    port: 2181
  - name: server
    port: 2888
  - name: leader-election
    port: 3888
  selector:
    app: zk
