apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-zk-1-pv
  labels:
    type: datadir-zk-1-pv 
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /dingxin/data/zk1/data

