apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-zk-2-pv
  labels:
    type: datadir-zk-2-pv 
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /dingxin/data/zk2/data

