apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filestorage-data-pvc 
  namespace: dingxin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      type: filestorage-data-pv

