apiVersion: v1
kind: PersistentVolume
metadata:
  name: filestorage-log-pv
  labels:
    type: filestorage-log-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /dingxin/data/filestorage/log

