apiVersion: v1
kind: PersistentVolume
metadata:
  name: dingxin-mongodb-storage-pv
  labels:
    type: dingxin-mongodb-storage
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /dingxin/data/mongodb

