apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dingxin-mongodb-pvc 
  namespace: dingxin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      type: dingxin-mongodb-storage

