apiVersion: v1
kind: PersistentVolume
metadata:
  name: dingxin-nginx 
  labels:
    type: dingxin-nginx-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /dingxin/data/nginx

