apiVersion: v1
kind: PersistentVolume
metadata:
  name: dingxin-db-storage-pv
  labels:
    type: dingxin-db-storage
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /dingxin/data/storage

