apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: core-log-pvc 
  namespace: dingxin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      type: core-log-pv

