apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dingxin-nginx-pvc 
  namespace: dingxin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: dingxin-nginx-pv

