apiVersion: v1
kind: Service
metadata:
  namespace: dingxin
  name: dingxin-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32180
    protocol: TCP
    name: http
  selector:
    app: dingxin-nginx 
