apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  namespace: dingxin
  name: codis-server
spec:
  serviceName: codis-server
  replicas: 2 
  selector:
    matchLabels:
      app: codis-server 
  template:
    metadata:
      labels:
        app: codis-server
    spec:
      containers:
      - name: codis-server
        image: harbor-ui:30814/dingchat/dx-codis-server:3.1.0 
        imagePullPolicy: IfNotPresent
        env:
        - name: PODIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 6379
          name: service-port
#        resources:
#          limits:
#            cpu: "2"
#            memory: 6Gi
#          requests:
#            cpu: "0.1"
#            memory: 0.1Gi
